### ISSUE TITLE
Can you release the source code of imdb data generation?

### ISSUE THREAD

**Issue by waizei** [guanghuixu/CRN_tvqa#2]
## ❓ Questions and Help
i need to do some further work,thanks

**Comment by guanghuixu** [comment]
Sorry, I don't quite understand your needs. The imdb file should be provided by the standard data set, please refer to the README for the code to calculate the edge feature.
bash scripts/process_dataset.sh crn_textvqa data/crn_textvqa/imdb/imdb_train_ocr_en.npy

**Comment by waizei** [comment]
it seems that some attributes do not appear in the standard data set such as 'obj_normalized_boxes'

**Comment by waizei** [comment]
maybe the dataset i used is old version,i will check it

**Comment by guanghuixu** [comment]
The imdb file can be found in M4C:https://github.com/ronghanghu/mmf/tree/project/m4c_captioner_pre_release/projects/M4C

Also, you can refer to https://github.com/guanghuixu/CRN_tvqa/blob/master/pythia/datasets/vqa/crn_textvqa/dataset.py#L134 and https://github.com/guanghuixu/CRN_tvqa/blob/master/pythia/utils/dataset_utils.py#L7
