### ISSUE TITLE
GPU out pf memory 

### ISSUE THREAD

**Issue by FJGEODEV** [guanghuixu/CRN_tvqa#3]
## ❓ Questions and Help

Hi, thanks for the good work, very impressive. I have a question about hardware. 

I have two Nivida Quadro P5000 (16GB) for training, however, I had some out-of-memory issues:

`RuntimeError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 15.90 GiB total capacity; 15.16 GiB already allocated; 10.75 MiB free; 150.03 MiB cached)`

Before I run the codes, there were no extra scripts occupying GPU. Just wondering which GPU you used for the training and inference?

If I want to train with my current GPUs, which parameter I need to change inorder to fit to my GPU memory.

Thanks.

**Comment by guanghuixu** [comment]
I run the code using 4 Tesla 12GB. You can try to use small batch size.
