### ISSUE TITLE
No such File error in edge_feat

### ISSUE THREAD

**Issue by absterk** [guanghuixu/CRN_tvqa#4]
## ❓ Questions and Help
Hi, thanks for sharing your work. 
I ran into a problem while training your model. It seems like some npy files are missing. 
Because the file is under crn_textvqa I was wondering if you could check the error I'm getting? 

Here is the error message that I'm getting: 
No such file or directory:  data/crn_textvqa/edge_feat/train/3100b88584dba89b.npy

Thank you

**Comment by guanghuixu** [comment]
The edge feature can be obtained by folllowing way:
```
# calculate the edge features for [train, val, test] split
bash scripts/process_dataset.sh crn_textvqa data/crn_textvqa/imdb/imdb_train_ocr_en.npy
```
(This repo is too old ...

**Comment by absterk** [comment]
Thanks for your response. 
I did follow the command so I'm not sure why I'm getting the error.

**Comment by guanghuixu** [comment]
```
bash scripts/process_dataset.sh crn_textvqa data/crn_textvqa/imdb/imdb_train_ocr_en.npy
bash scripts/process_dataset.sh crn_textvqa data/crn_textvqa/imdb/imdb_val_ocr_en.npy
bash scripts/process_dataset.sh crn_textvqa data/crn_textvqa/imdb/imdb_test_ocr_en.npy
```

**Comment by zc1326387279** [comment]
Hi, I'm glad you can share your code with us. However, I encountered the problem of 'CRN' object has no attribute 'module' in the training process. Each data set will report this error, so I cannot solve it. Could you please help me?

**Comment by zc1326387279** [comment]
Hi, I'm glad you can share your code with us. When I copied your code, I noticed that the features of test_task1 and test_task2 were missing from the object characteristics file m4c_stvqa_obj_frcn_features in the dataset STVQA. Could you please give me a more comprehensive data set file?

**Comment by zc1326387279** [comment]
Hi, I'm glad you shared your code with us. When I copied your code, I noticed that the features of test_task1 and test_task2 were missing from the object characteristics file m4c_stvqa_obj_frcn_features in the STVQA dataset. Could you please give me a more comprehensive data set file?

**Comment by guanghuixu** [comment]
All the features are provided by [M4C](https://github.com/ronghanghu/mmf/tree/28e48ce489605741a5de7d069ecfa457a5428512/projects/M4C). In his repo, you should be able to find what you are looking for.

**Comment by zc1326387279** [comment]
> All the features are provided by [M4C](https://github.com/ronghanghu/mmf/tree/28e48ce489605741a5de7d069ecfa457a5428512/projects/M4C). In his repo, you should be able to find what you are looking for.

Hello, I'm glad to receive your reply. I entered the M4C data set of the project you gave me, but found only test_task3 and train files in the m4c_stvqa_obj_frcn_features file. However, the test_task1 and test_task2 files are also used in the code. How do you handle this during testing?

**Comment by guanghuixu** [comment]
As I remember, the features used in the three tasks of ST-VQA are the same, but the difficulty of the tasks is different. See the [ST-VQA challenge](https://rrc.cvc.uab.es/?ch=11&com=tasks) for more details.

```
ST-VQA introduces three novel tasks, namely strongly contextualized (Task 1), weakly contextualized (Task 2) and open vocabulary (Task 3), which gradually increase in difficulty
```

**Comment by zc1326387279** [comment]
> As I remember, the features used in the three tasks of ST-VQA are the same, but the difficulty of the tasks is different. See the [ST-VQA challenge](https://rrc.cvc.uab.es/?ch=11&com=tasks) for more details. ``` ST-VQA introduces three novel tasks, namely strongly contextualized (Task 1), weakly contextualized (Task 2) and open vocabulary (Task 3), which gradually increase in difficulty ```

Thank you very much for your answer. In the path you pointed out, I found the relevant files of STVQA data set, including the source files of images and problems. However, I found that the data set used in this project were all the characteristic '.npy 'files that had been processed, but what I gave were'.jpg 'image files and'.json 'problem files. What if I want them to be the same as task3?

**Comment by guanghuixu** [comment]
No, I didn't mean that. Through the description of the official website, it can be determined that the features of the three tasks are the same. You only need to use the features of task3 to do task1 and task2. If I'm not mistaken, task1 is the given option, task2 is the full vocabulary, and task3 is generated directly without the vocabulary. You need to see for yourself




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月4日(星期天) 下午5:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guanghuixu/CRN_tvqa] No such File error in edge_feat (Issue #4)





  
As I remember, the features used in the three tasks of ST-VQA are the same, but the difficulty of the tasks is different. See the ST-VQA challenge for more details. ST-VQA introduces three novel tasks, namely strongly contextualized (Task 1), weakly contextualized (Task 2) and open vocabulary (Task 3), which gradually increase in difficulty
  
Thank you very much for your answer. In the path you pointed out, I found the relevant files of STVQA data set, including the source files of images and problems. However, I found that the data set used in this project were all the characteristic '.npy 'files that had been processed, but what I gave were'.jpg 'image files and'.json 'problem files. What if I want them to be the same as task3?

**Comment by guanghuixu** [comment]
The images used for all three tasks are the same, so the object features and OCR features are the same

**Comment by zc1326387279** [comment]
> The images used for all three tasks are the same, so the object features and OCR features are the same

I thought about this, but when I tested task2 using task3's object features , I executed this command on task2: 
bash scripts/val_stvqa_task2.sh 3 stvqa_debug_task2 save/stvqa_debug_task2/crn_stvqa_crn/best.ckpt inference；
error is always reported: No such file or directory: '/textvqa/CRN_tvqa/pythia/.. /data/crn_stvqa/m4c_stvqa_obj_frcn_features/test_task3/VisualGenome/2/2402685.npy'

**Comment by zc1326387279** [comment]
At present, my experiments on STVQA data set are as follows:
Error when training on task1: RuntimeError: Sizes of tensors must match except in dimension 1. Got 50 and 150 (The offending index is 1);
On task2, there are problems with just testing, training and validation are normal;
Everything is normal on task3.

**Comment by guanghuixu** [comment]
Sorry, the details of this experiment are too old for me to remember. However, your training and validation on task2 are fine, and task1 is also fine, which should not be caused by missing feature files. It is recommended to check first, if only some files are missing or all of them are not there

**Comment by zc1326387279** [comment]
> Sorry, the details of this experiment are too old for me to remember. However, your training and validation on task2 are fine, and task1 is also fine, which should not be caused by missing feature files. It is recommended to check first, if only some files are missing or all of them are not there

Ok, thank you very much for your answer.

**Comment by zc1326387279** [comment]
Hi, I have now done the training, validation and testing, but after the validation and testing, I have generated JSON files, what should I do if I want to use them to evaluate the performance metrics of the training model?

**Comment by guanghuixu** [comment]
In the shell terminal or log file, the performance metrics of the validation set is printed. For test sets, we don't have labels and need to submit to the corresponding Challenge leaderboard

**Comment by guanghuixu** [comment]
If you want to test your own data, please refer to [metrics.py](https://github.com/guanghuixu/CRN_tvqa/blob/master/pythia/modules/metrics.py)

**Comment by zc1326387279** [comment]
Hello, so if I want to test the effects of my model on textvqa, stvqa and ocrvqa, do I have to upload it to a challenge to test it?

**Comment by guanghuixu** [comment]
Sorry, do you want to know the performance of your model on the test set? If yes, the Challenge leaderboard is required. If it is only a validation set, you can see the log file




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guanghuixu/CRN_tvqa] No such File error in edge_feat (Issue #4)





 
Hello, so if I want to test the effects of my model on textvqa, stvqa and ocrvqa, do I have to upload it to a challenge to test it?

**Comment by zc1326387279** [comment]
So if I just want to test the performance of baseline Model M4C trained on my server, do I upload the test json file directly to the challenge? Is this a bad behavior? And I find that I need to introduce my own methods when I upload.
