### ISSUE TITLE
requirements.tx

### ISSUE THREAD

**Issue by baochi0212** [guanghuixu/CRN_tvqa#5]
![image](https://github.com/guanghuixu/CRN_tvqa/assets/77192945/3275895e-19a3-48f7-8011-83c2399e274c)

I follow the installation guideline, still encouter this though. Please help! thanks

**Comment by guanghuixu** [comment]
[requirements.txt](https://github.com/ronghanghu/mmf/blob/project/m4c_captioner_pre_release/requirements.txt)
